spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  jwt:
    secret:
      key: 00C49vjBEiNEmODEZoDgkuQ/nNl6pNwDVrpNv9TqJJo=

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: jbWWQFKM2otmcR1TaoD0
            client-secret: vfq4y2gewE
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-name: google
            client-id: 794719293509-ll1nb977kodhilbvgd5e29ce1j7m9g2u.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    root: INFO


