spring:
  cloud:
    config:
      enabled: false

  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_starbucks_delivery
    username: root
    password: 12341234
